services:
  - type: web
    name: pokemon-tcg-scraper
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
      - key: TELEGRAM_CHAT_ID
