services:
  - type: web
    name: pokemon-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python apply_patch.py
    startCommand: python pokemon_scraper.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
